name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read # allow read access to the content for analysis.
      checks: write # allow write access to checks to allow the action to annotate code in the PR.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
